using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Tools
{
    public class EnumObtenebration
    {
        public static readonly string OBTENEBRATION_KEY = "OBTENEBRATION_KEY";
        public static readonly string OBTENEBRATION_TEST_SCORE = "OBTENEBRATION_TEST_SCORE";

        public static readonly string OBTENEBRATION_NAME = "OBTENEBRATION_NAME";
        public static readonly string OBTENEBRATION_DESCRIPTION = "OBTENEBRATION_DESCRIPTION";

        public static readonly string OBTENEBRATION_POWER_1_NAME = "OBTENEBRATION_POWER_1_NAME";
        public static readonly string OBTENEBRATION_POWER_2_NAME = "OBTENEBRATION_POWER_2_NAME";
        public static readonly string OBTENEBRATION_POWER_3_NAME = "OBTENEBRATION_POWER_3_NAME";
        public static readonly string OBTENEBRATION_POWER_4_NAME = "OBTENEBRATION_POWER_4_NAME";
        public static readonly string OBTENEBRATION_POWER_5_NAME = "OBTENEBRATION_POWER_5_NAME";

        public static readonly string OBTENEBRATION_POWER_1_DESCRIPTION = "OBTENEBRATION_POWER_1_DESCRIPTION";
        public static readonly string OBTENEBRATION_POWER_2_DESCRIPTION = "OBTENEBRATION_POWER_2_DESCRIPTION";
        public static readonly string OBTENEBRATION_POWER_3_DESCRIPTION = "OBTENEBRATION_POWER_3_DESCRIPTION";
        public static readonly string OBTENEBRATION_POWER_4_DESCRIPTION = "OBTENEBRATION_POWER_4_DESCRIPTION";
        public static readonly string OBTENEBRATION_POWER_5_DESCRIPTION = "OBTENEBRATION_POWER_5_DESCRIPTION";

        public static readonly string OBTENEBRATION_POWER_1_SYSTEM = "OBTENEBRATION_POWER_1_SYSTEM";
        public static readonly string OBTENEBRATION_POWER_2_SYSTEM = "OBTENEBRATION_POWER_2_SYSTEM";
        public static readonly string OBTENEBRATION_POWER_3_SYSTEM = "OBTENEBRATION_POWER_3_SYSTEM";
        public static readonly string OBTENEBRATION_POWER_4_SYSTEM = "OBTENEBRATION_POWER_4_SYSTEM";
        public static readonly string OBTENEBRATION_POWER_5_SYSTEM = "OBTENEBRATION_POWER_5_SYSTEM";

        public static readonly string OBTENEBRATION_POWER_1_FOCUS_DESCRIPTION = "OBTENEBRATION_POWER_1_FOCUS_DESCRIPTION";
        public static readonly string OBTENEBRATION_POWER_2_FOCUS_DESCRIPTION = "OBTENEBRATION_POWER_2_FOCUS_DESCRIPTION";
        public static readonly string OBTENEBRATION_POWER_3_FOCUS_DESCRIPTION = "OBTENEBRATION_POWER_3_FOCUS_DESCRIPTION";
        public static readonly string OBTENEBRATION_POWER_4_FOCUS_DESCRIPTION = "OBTENEBRATION_POWER_4_FOCUS_DESCRIPTION";
        public static readonly string OBTENEBRATION_POWER_5_FOCUS_DESCRIPTION = "OBTENEBRATION_POWER_5_FOCUS_DESCRIPTION";

        public static readonly string OBTENEBRATION_POWER_1_EXCEPTIONALSUCCESS = "OBTENEBRATION_POWER_1_EXCEPTIONALSUCCESS";
        public static readonly string OBTENEBRATION_POWER_2_EXCEPTIONALSUCCESS = "OBTENEBRATION_POWER_2_EXCEPTIONALSUCCESS";
        public static readonly string OBTENEBRATION_POWER_3_EXCEPTIONALSUCCESS = "OBTENEBRATION_POWER_3_EXCEPTIONALSUCCESS";
        public static readonly string OBTENEBRATION_POWER_4_EXCEPTIONALSUCCESS = "OBTENEBRATION_POWER_4_EXCEPTIONALSUCCESS";
        public static readonly string OBTENEBRATION_POWER_5_EXCEPTIONALSUCCESS = "OBTENEBRATION_POWER_5_EXCEPTIONALSUCCESS";
    }
}
