// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CorrectifPower : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CorrectifPower));
        
        string IMigrationMetadata.Id
        {
            get { return "201909262206538_Correctif-Power"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
